[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd /app/GoalConnect && npm ci"]

[phases.build]
cmds = ["cd /app/GoalConnect && npm run build"]

[start]
cmd = "cd /app/GoalConnect && npm run db:migrate && npm run start"
